spring:
    sql:
      init:
        platform: mariadb
        encoding: UTF-8
        mode: always
#    datasource:
#      driver-class-name: org.mariadb.jdbc.Driver
#      url: jdbc:mariadb://localhost:3377/bhr
#      username: root
#      password: maria
    #JPA
    jpa:
      hibernate:
        ddl-auto: create
      generate-ddl: false
      show-sql: true
    # private yml import
    profiles:
      include: private
    jwt:
      secret: lskfjalijefnalavagiowrngwoianwefokldfmaefieanfwwoeifnwnfoeinfowinf

server:
  port: 8000


