spring:
  jwt:
    secret: ${JWT_SECRET}
  sql:
    init:
      data-locations: classpath*:data.sql
      platform: mariadb
      encoding: UTF-8
      mode: always
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    defer-datasource-initialization: true


server:
  port: 8000

logging:
  level:
    org:
      springframework:
        web: DEBUG