spring:
  jwt:
    secret: awsec2docker
  sql:
    init:
      data-locations: classpath*:data.sql
      platform: mariadb
      encoding: UTF-8
      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ec2-43-202-65-100.ap-northeast-2.compute.amazonaws.com:6000/exmple-database
    username: example-user
    password: my_cool_secret

  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    defer-datasource-initialization: true


server:
  port: 8000