spring:
  jwt:
    secret: abc
  sql:
    init:
      data-locations: classpath*:data.sql
      platform: mariadb
      encoding: UTF-8
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MariaDB
    username: sa
    password:
  #JPA
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8000